retoohs/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib import admin

urlpatterns = [
    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    # url('^avatar/', include('avatar.urls')),
    url(r'^{}/'.format(getattr(settings, 'ADMIN_URL', 'admin')), admin.site.urls),
    url(r'^dashboard/forums/', include('lbforum.urls')),
    url(r'^dashboard/', include('ss.urls', namespace='ss')),
    url(r'^', include('main.urls')),
    url(r'^attachments/', include('lbattachment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ss/urls.py
from django.conf.urls import url
from ss import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^check-in$', views.CheckIn.as_view(), name='check_in'),
    url(r'^create$', views.SSUserCreate.as_view(), name='create'),
    url(r'^invites/create$', views.InviteCodeCreate.as_view(), name='create_invite_code'),
    url(r'^invites', views.InviteCodeList.as_view(), name='invite_code_list'),
    url(r'^nodes$', views.NodeList.as_view(), name='node_list'),
    url(r'^nodes/create$', views.NodeCreate.as_view(), name='node_create'),
    url(r'^qr-code$', views.get_ss_qr, name='qr_code'),
]

ss/models.py
import datetime
from random import choice
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core import validators
from django.dispatch import receiver
from django.shortcuts import resolve_url
# from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from ss.utils import random_long_string, random_short_string

PLAN_CHOICES = (
    ('free', 'Free'),
)
METHOD_CHOICES = (
    ('aes-256-cfb', 'aes-256-cfb'),
    ('rc4-md5', 'rc4-md5'),
    ('salsa20', 'salsa20'),
    ('chacha20', 'chacha20'),
)
STATUS_CHOICES = (
    ('ok', '好用'),
    ('slow', '不好用'),
    ('fail', '坏了'),
)


# Create your models here.
class SSUser(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ss_user',
    )
    plan = models.CharField(
            '套餐',
            max_length=32,
            default='free',
            choices=PLAN_CHOICES,
    )
    last_check_in_time = models.DateTimeField(
            '最后签到时间',
            null=True,
            default=datetime.datetime.fromtimestamp(0),
            editable=False,
    )
    invite_code = models.OneToOneField(
            'InviteCode',
            on_delete=models.SET_NULL,
            related_name='used_by',
            null=True,
    )
    # ShadowSocks fields
    password = models.CharField(
            'ShadowSocks密码',
            max_length=32,
            validators=[validators.MinLengthValidator(6), ],
            default=random_short_string,
            db_column='passwd',
    )
    port = models.IntegerField(
            '端口',
            db_column='port',
            unique=True,
    )
    last_use_time = models.IntegerField(
            '最后使用时间',
            default=0,
            editable=False,
            help_text='时间戳',
            db_column='t',
    )
    upload_traffic = models.BigIntegerField(
            '上传流量',
            default=0,
            db_column='u',
    )
    download_traffic = models.BigIntegerField(
            '下载流量',
            default=0,
            db_column='d',
    )
    transfer_enable = models.BigIntegerField(
            '总流量',
            default=settings.DEFAULT_TRAFFIC,
            db_column='transfer_enable',
    )
    switch = models.BooleanField(
            'switch',
            default=True,
            db_column='switch'
    )
    enable = models.BooleanField(
            '开启',
            default=True,
            db_column='enable'
    )

    def __str__(self):
        return self.user.username

    def get_last_use_time(self):
        return timezone.datetime.fromtimestamp(self.last_use_time)

    def get_traffic(self):
        return '{:.2f}'.format((self.download_traffic + self.upload_traffic) / 1024 / 1024)

    def get_transfer(self):
        return '{:.2f}'.format(self.transfer_enable / 1024 / 1024 / 1024)

    def get_unused_traffic(self):
        return '{:.2f}'.format((self.transfer_enable - self.download_traffic - self.upload_traffic) / 1024 / 1024 / 1024)

    def get_used_percentage(self):
        return (self.download_traffic + self.upload_traffic) / self.transfer_enable * 100

    def can_check_in(self):
        return timezone.now() - datetime.timedelta(days=1) > self.last_check_in_time

    @classmethod
    def get_absolute_url(cls):
        return resolve_url('ss:index')

    def clean(self):
        # limit: 1024 < port < 50000
        if self.port:
            if not 1024 < self.port < 5000:
                raise ValidationError('端口必须大于1024,小于50000')
        else:
            max_port_user = SSUser.objects.order_by('-port').first()
            if max_port_user:
                self.port = max_port_user.port + choice([2, 3])
            else:
                self.port = settings.START_PORT

    class Meta:
        verbose_name = 'SS帐户'
        ordering = ('-last_check_in_time',)
        db_table = 'user'


class InviteCode(models.Model):
    code = models.CharField(
            '邀请码',
            primary_key=True,
            blank=True,
            max_length=40,
            default=random_long_string,
            # validators=[validators.MinLengthValidator(64), ],
    )
    user = models.ForeignKey(
            'SSUser',
            on_delete=models.CASCADE,
            related_name='invite_codes',
            null=True,
            blank=True,
            help_text='不选择用户生成的验证码将公开',
    )
    time_created = models.DateTimeField(
            '创建时间',
            editable=False,
            auto_now_add=True,
    )

    def clean(self):
        # generate code if code exists
        code_length = len(self.code or '')
        if 0 < code_length < 16:
            self.code = '{}{}'.format(
                    self.code,
                    random_long_string()
            )
        else:
            self.code = None

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.clean()
        return super(InviteCode, self).save(force_insert, force_update, using, update_fields)

    class Meta:
        verbose_name = '邀请码'
        ordering = ('-time_created',)


class Node(models.Model):
    name = models.CharField(
            '名字',
            max_length=32,
    )
    plan = models.CharField(
            '类型',
            max_length=32,
            default='free',
            choices=PLAN_CHOICES,
    )
    server = models.CharField(
            '服务器',
            max_length=128,
    )
    method = models.CharField(
            '加密类型',
            max_length=32,
            default='aes-256-cfb',
            choices=METHOD_CHOICES,
    )
    info = models.CharField(
            '简介',
            max_length=1024,
            blank=True,
            null=True,
    )
    status = models.CharField(
            '状态',
            max_length=32,
            default='ok',
            choices=STATUS_CHOICES,
    )
    weight = models.IntegerField(
            '排序',
            default=1,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-weight',)
        verbose_name = '节点'


@receiver(post_save, sender=SSUser)
def remove_invite_code_after_use(instance, created, **kwargs):
    if created:
        if instance.invite_code:
            instance.invite_code.delete()

ss/forms.py
from django import forms
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from ss.models import SSUser, InviteCode, Node


class CrispyFormMixin(object):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', '确定'))
        super(CrispyFormMixin, self).__init__(*args, **kwargs)


class SSUserForm(CrispyFormMixin, forms.ModelForm):
    invite_code = forms.CharField(max_length=40, min_length=24, label='邀请码')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        code = kwargs.pop('code', False)
        super(SSUserForm, self).__init__(*args, **kwargs)
        if code:
            self.fields['invite_code'].initial = code

    def save(self, commit=True):
        self.instance.user = self.user
        return super(SSUserForm, self).save(commit)

    class Meta:
        model = SSUser
        fields = ('password', 'invite_code')


class InviteCodeForm(CrispyFormMixin, forms.ModelForm):
    number = forms.IntegerField(label='数量', initial=1, required=False)
    code = forms.CharField(label='前缀', max_length=32, required=False)

    def __init__(self, *args, **kwargs):
        self.instances = []
        self.instance_number = 1
        super(InviteCodeForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(InviteCodeForm, self).clean()
        self.instance_number = cleaned_data.pop('number')
        return cleaned_data

    def save(self, commit=True):
        """
        Create many InviteCode instances
        :param commit:
        :return:
        """
        if self.errors:
            raise ValueError('data did not validate')
        code = self.cleaned_data.get('code')
        user = self.cleaned_data.get('user')
        for _ in range(self.instance_number):
            obj = self._meta.model.objects.create(code=code, user=user)
            self.instances.append(obj)
        self.instance = self.instances[0]
        return self.instance

    class Meta:
        model = InviteCode
        fields = ('user', 'code', 'number')


class NodeForm(CrispyFormMixin, forms.ModelForm):
    class Meta:
        model = Node
        fields = '__all__'

ss/views.py
import random
import qrcode
import base64
import datetime
from io import StringIO
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.http.response import JsonResponse, HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.views.decorators import staff_member_required
from ss.models import SSUser, InviteCode, Node
from ss import forms


class StaffMixin(object):
    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated() or not user.is_staff:
            raise PermissionDenied

        return super(StaffMixin, self).dispatch(request, *args, **kwargs)


class EmailVerifiedRequiredMixin(LoginRequiredMixin):
    login_url = reverse_lazy('my')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated() or not request.user.email_verified:
            messages.add_message(request, messages.WARNING, '需要激活邮箱。')
            return self.handle_no_permission()
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class SSLoginRequiredMixin(LoginRequiredMixin):
    login_url = reverse_lazy('ss:create')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated() or not getattr(request.user, 'ss_user', None):
            messages.add_message(
                request,
                messages.WARNING,
                '需要使用<a href="{}">邀请码</a>激活Shadowsocks账号。'.format(reverse_lazy('ss:invite_code_list')))
            return self.handle_no_permission()
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class Index(SSLoginRequiredMixin, TemplateView):
    template_name = 'ss/index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context.update({'page_msg': 'User Center', 'page_header': '用户中心'})
        return context


class SSUserCreate(EmailVerifiedRequiredMixin, generic.CreateView):
    model = SSUser
    form_class = forms.SSUserForm

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'ss_user'):
            return redirect('ss:index')
        return super(SSUserCreate, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        # add request.user to form init kwargs
        kwargs = super(SSUserCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        if self.request.GET.get('code'):
            kwargs['code'] = self.request.GET.get('code')
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(SSUserCreate, self).get_context_data(**kwargs)
        context.update({'page_msg': 'Initial Shadowsocks', 'page_header': '开始科学上网'})
        return context


class InviteCodeCreate(LoginRequiredMixin, StaffMixin, generic.CreateView):
    model = InviteCode
    form_class = forms.InviteCodeForm
    success_url = reverse_lazy('ss:invite_code_list')

    def dispatch(self, request, *args, **kwargs):
        return super(InviteCodeCreate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(InviteCodeCreate, self).get_context_data(**kwargs)
        context.update({'page_msg': 'Add Invitation Codes', 'page_header': '添加邀请码'})
        return context


class InviteCodeList(LoginRequiredMixin, generic.ListView):
    model = InviteCode

    def get_queryset(self):
        return InviteCode.objects.filter(user=None).order_by('time_created')[:15]

    def get_context_data(self, **kwargs):
        context = super(InviteCodeList, self).get_context_data(**kwargs)
        context.update({'page_msg': 'Invitation Codes', 'page_header': '邀请码'})
        return context


class NodeList(SSLoginRequiredMixin, generic.ListView):
    model = Node

    def get_context_data(self, **kwargs):
        context = super(NodeList, self).get_context_data(**kwargs)
        context.update({'page_header': '节点列表', 'page_msg': 'Node List'})
        return context


class NodeCreate(LoginRequiredMixin, StaffMixin, generic.CreateView):
    model = Node
    form_class = forms.NodeForm
    success_url = reverse_lazy('ss:node_list')

    def get_context_data(self, **kwargs):
        context = super(NodeCreate, self).get_context_data(**kwargs)
        context.update({'page_msg': 'Create Node', 'page_header': '添加节点'})
        return context


class CheckIn(SSLoginRequiredMixin, generic.View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CheckIn, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        user = getattr(request.user, 'ss_user', None)
        if timezone.now() - datetime.timedelta(days=1) > user.last_check_in_time:
            if user.transfer_enable < 2 * 1024 * 1024 * 1024:
                traffic = int(1024 * 1024 * 1024 + random.random() * 100 * 1024 * 1024)
            else:
                traffic = int(random.random() * 100 * 1024 * 1024)
            user.transfer_enable += traffic
            user.last_check_in_time = timezone.now()
            user.save()
            return JsonResponse({'msg': '获得了{:.2f}MB流量'.format(traffic / 1024 / 1024)})
        else:
            raise PermissionDenied('24小时内签到一次')


def get_ss_qr(request):
    if request.user.is_anonymous():
        return JsonResponse({'error': 'unauthorized'})

    if not hasattr(request.user, 'ss_user'):
        return JsonResponse({'error': 'no linked shadowsocks account'})
    ss_user = request.user.ss_user

    if request.GET.get('nid'):
        try:
            node = Node.objects.get(pk=request.GET.get('nid'))
        except Node.DoesNotExist:
            return JsonResponse({'error': 'node not exist'})
    else:
        node = Node.objects.all().order_by('-weight')
        if node:
            node = node[0]
        else:
            return JsonResponse({'error': 'no node at all'})

    password = '{}:{}@{}:{}'.format(node.method, ss_user.password, node.server, ss_user.port)
    img = qrcode.make('ss://{}'.format(base64.b64encode(bytes(password, 'utf8')).decode('ascii')))
    response = HttpResponse(content_type="image/png")
    img.save(response)
    return response

templates/ss/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
            <!-- START PROGRESS BARS -->
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-solid">
                        <div class="box-header">
                            <h3 class="box-title">公告&FAQ</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <p>流量不会重置，可以通过签到获取流量。</p>
                            <p>流量可以通过签到获取，基本每天可以用1G流量。</p>
			                <p>服务器出问题的话可以微博私信我<a href="http://www.weibo.com/u/1851837275">有药吃</a>。</p>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col (right) -->

                <div class="col-md-6">
                    <div class="box box-solid">
                        <div class="box-header">
                            <h3 class="box-title">流量使用情况</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <p> 已用流量：{{ user.ss_user.get_traffic }}MB </p>
                            <div class="progress progress-striped">
                                <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: {{ user.ss_user.get_used_percentage }}%">
                                    <span class="sr-only">Transfer</span>
                                </div>
                            </div>
                            <p> 可用流量：{{ user.ss_user.get_transfer }}GB </p>
                            <p> 剩余流量：{{ user.ss_user.get_unused_traffic }}GB </p>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col (left) -->



                <div class="col-md-6">
                    <div class="box box-solid">
                        <div class="box-header">
                            <h3 class="box-title">签到获取流量</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <p> 24小时内可以签到一次。</p>
                            {% if user.ss_user.can_check_in %}
                            <p id="checkin-btn"> <button id="checkin" class="btn btn-success  btn-flat">签到</button></p>
                            {% else %}
                            <p><a class="btn btn-success btn-flat disabled" href="#">不能签到</a> </p>
                            {% endif %}
                            <p id="checkin-msg" ></p>
                            <p>上次签到时间：<code>{{ user.ss_user.last_check_in_time }}</code></p>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col (right) -->

                <div class="col-md-6">
                    <div class="box box-solid">
                        <div class="box-header">
                            <h3 class="box-title">连接信息</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <p> 端口：<code>{{ user.ss_user.port }}</code> </p>
                            <p> 密码：{{ user.ss_user.password }} </p>
                            <p> 套餐：<span class="label label-info">{{ user.ss_user.get_plan_display }}</span> </p>
                            <!-- Button trigger modal -->
                            <p> 自动设置:
                                <button type="button" class="btn btn-sm" data-toggle="modal" data-target="#myModal" style="background-color: #39C5BB;border-color: #39C5BB; color: white">
                                    查看二维码
                                </button>
                            </p>
                            <p> 最后使用时间：<code>{{ user.ss_user.get_last_use_time }}</code> </p>

                            <!-- Modal -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel" style="text-align: center">
                                                用各种客户端扫一下
                                            </h4>
                                        </div>
                                        <div class="modal-body">
                                            <img src="{% url 'ss:qr_code' %}" height="200" width="200" style="display: block;margin: 0 auto;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col (right) -->
            </div><!-- /.row -->
            <!-- END PROGRESS BARS -->
{#    <div class="card">#}
{#        {% if user.is_authenticated and user.ss_user %}#}
{#            port: {{ user.ss_user.port }}#}
{#            password: {{ user.ss_user.password }}#}
{#            transfer: {{ user.ss_user.transfer_enable }}#}
{#            upload_traffic: {{ user.ss_user.upload_traffic }}#}
{#            download_traffic: {{ user.ss_user.download_traffic }}#}
{#        {% else %}#}
{#            <h4><a href="{% url 'ss:create' %}">Register ShadowSocks Account</a></h4>#}
{#        {% endif %}#}
{#    </div>#}
{% endblock %}

{% block footer %}
    <script>
    $(document).ready(function(){
        $("#checkin").click(function(){
            $.ajax({
                type:"POST",
                url:"{% url 'ss:check_in' %}",
                dataType:"json",
                success:function(data){
                    $("#checkin-msg").html(data.msg);
                    $("#checkin-btn").hide();
                },
                error:function(jqXHR){
                    alert("发生错误："+jqXHR.status);
                }
            })
        })
    })
</script>
{% endblock %}

templates/ss/invitecode_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="card">
    <div class="card-block">
        {% crispy form %}
    </div>
</div>
{% endblock %}

templates/ss/invitecode_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
{#    <div class="card col-md-6">#}
{#        <h4 class="card-title">Invite Codes:</h4>#}
{#        <div class="table-responsive">#}
{#            <table class="table table-striped">#}
{#                <thead>#}
{#                <tr>#}
                    {#                <th>###</th>#}
{#                    <th>邀请码</th>#}
{#                    <th>状态</th>#}
{#                </tr>#}
{#                </thead>#}
{#                <tbody>#}
{#                {% for code in object_list %}#}
{#                    <tr>#}
                        {#                    <td>0</td>#}
{#                        <td><a href="{% url 'ss:create' %}?code={{ code.code }}">{{ code.code }}</a></td>#}
{#                        <td>可用</td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
{#    </div>#}
    <div class="row">
        <div class="col-md-6">
            <!-- TABLE: LATEST CODES -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">选择一组邀请码注册</h3>
                    <br>

{#                    <div class="box-tools pull-right">#}
{#                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i#}
{#                                class="fa fa-minus"></i>#}
{#                        </button>#}
{#                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>#}
{#                        </button>#}
{#                    </div>#}
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table no-margin">
                            <thead>
                            <tr>
                                {#                        <th>Order ID</th>#}
                                {#                        <th>Item</th>#}
                                {#                        <th>Status</th>#}
                                <th>邀请码</th>
                                <th>状态</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for code in object_list %}
                                <tr>
                                    {#                            <td><a href="pages/examples/invoice.html">OR9842</a></td>#}
                                    {#                            <td>Call of Duty IV</td>#}
                                    {#                            <td><span class="label label-success">Shipped</span></td>#}
                                    {#                            <td>#}
                                    {#                                <div class="sparkbar" data-color="#00a65a" data-height="20">90,80,90,-70,61,-83,63</div>#}
                                    {#                            </td>#}
                                    <td><a href="{% url 'ss:create' %}?code={{ code.code }}">{{ code.code }}</a></td>
                                    <td>可用</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                {#        <!-- /.box-body -->#}
                {#        <div class="box-footer clearfix">#}
                {#            <a href="javascript:void(0)" class="btn btn-sm btn-info btn-flat pull-left">Place New Order</a>#}
                {#            <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>#}
                {#        </div>#}
                {#        <!-- /.box-footer -->#}
            </div>
        </div>
    </div>

{% endblock %}

templates/ss/node_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-body">
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ss/node_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-solid">
                <div class="box-header">
                    <i class="fa fa-th-list"></i>
                    <h3 class="box-title">节点</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="callout callout-warning">
                        <h4>注意!</h4>
                        <p>请勿在任何地方公开节点地址！</p>
                    </div>
                    {% for node in node_list %}
                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs pull-right">
{#                                <li class="dropdown">#}
{#                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">#}
{#                                        操作 <span class="caret"></span>#}
{#                                    </a>#}
{#                                    <ul class="dropdown-menu">#}
{#                                        <li role="presentation"><a role="menuitem" target="_blank" tabindex="-1"#}
{#                                                                   href="node_json.php?id=3">配置文件</a></li>#}
{#                                        <li role="presentation"><a role="menuitem" target="_blank" tabindex="-1"#}
{#                                                                   href="node_qr.php?id=3">二维码</a></li>#}
{#                                    </ul>#}
{#                                </li>#}
                                <li class="pull-left header"><i class="fa fa-angle-right"></i>{{ node.name }}</li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1-1">
                                    <p><a class="btn btn-xs bg-purple btn-flat margin" href="#">地址:</a>
                                        <code>{{ node.server }}</code>
                                        <a class="btn btn-xs bg-orange btn-flat margin" href="#">{{ node.get_status_display }}</a>
                                        <a class="btn btn-xs bg-green btn-flat margin" href="#">{{ node.method }}</a>
                                    </p>
                                    <p>{{ node.info }}</p>
                                </div><!-- /.tab-pane -->
                            </div><!-- /.tab-content -->
                        </div><!-- nav-tabs-custom -->
                    {% endfor %}
                </div><!-- /.box-body -->


            </div><!-- /.box -->
        </div><!-- /.col (left) -->

        <div class="col-md-6">
            <div class="box box-solid">
                <div class="box-header">
                    <i class="fa fa-code"></i>
                    <h3 class="box-title">Pro节点</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="callout callout-warning">
                        <h4>注意!</h4>
                        <p>....</p>
                    </div>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col (right) -->

    </div><!-- /.row -->

{% endblock %}

templates/ss/ssuser_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-body">
                    <h4 class="box-title">创建Shadowsocks账号</h4>
                    <br>
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}