retoohs/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib import admin

urlpatterns = [
    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    # url('^avatar/', include('avatar.urls')),
    url(r'^{}/'.format(getattr(settings, 'ADMIN_URL', 'admin')), admin.site.urls),
    url(r'^dashboard/forums/', include('lbforum.urls')),
    url(r'^dashboard/', include('ss.urls', namespace='ss')),
    url(r'^', include('main.urls')),
    url(r'^attachments/', include('lbattachment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ss/urls.py
from django.conf.urls import url
from ss import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^check-in$', views.CheckIn.as_view(), name='check_in'),
    url(r'^create$', views.SSUserCreate.as_view(), name='create'),
    url(r'^invites/create$', views.InviteCodeCreate.as_view(), name='create_invite_code'),
    url(r'^invites', views.InviteCodeList.as_view(), name='invite_code_list'),
    url(r'^nodes$', views.NodeList.as_view(), name='node_list'),
    url(r'^nodes/create$', views.NodeCreate.as_view(), name='node_create'),
    url(r'^qr-code$', views.get_ss_qr, name='qr_code'),
]

templates/__base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Retoohs</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% block stylesheet %}{% endblock %}
  {% block head %}{% endblock %}
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>R</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>retoohs</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="/" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'img/gravatar.png' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'img/gravatar.png' %}" class="img-circle" alt="User Image">

                <p>
                  {{ request.user.username }}
                  <small>加入时间：{{ request.user.joined_at }}</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{% url 'my' %}" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'logout' %}" class="btn btn-default btn-flat">登出</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'img/gravatar.png' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ request.user.username }}</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header"></li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{% url 'ss:index' %}"><i class="fa fa-user"></i> <span>用户中心</span></a></li>
        <li><a href="{% url 'ss:node_list' %}"><i class="fa fa-link"></i> <span>节点列表</span></a></li>
{#        <li><a href="#"><i class="fa fa-circle-o"></i> <span>修改资料</span></a></li>#}
        <li><a href="{% url 'ss:invite_code_list' %}"><i class="fa fa-code-fork"></i> <span>邀请码</span></a></li>
        <li><a href="{% url 'my' %}"><i class="fa fa-link"></i> <span>我的信息</span></a></li>
        <li><a href="{% url 'donate' %}"><i class="fa fa-link"></i> <span>捐赠</span></a></li>
        <li><a href="{% url 'lbforum_index' %}"><i class="fa fa-link"></i> <span>论坛</span></a></li>
          {% if request.user.is_staff %}
        <li><a href="{% url 'ss:node_create' %}"><i class="fa fa-link"></i> <span>节点编辑</span></a></li>
        <li><a href="#"><i class="fa fa-link"></i> <span>查看用户</span></a></li>
        <li><a href="{% url 'ss:create_invite_code' %}"><i class="fa fa-link"></i> <span>邀请管理</span></a></li>
        <li><a href="#"><i class="fa fa-gears"></i> <span>系统信息</span></a></li>
          {% endif %}
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
  {% if page_header or page_msg %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ page_header }}
        <small>{{ page_msg }}</small>
      </h1>
    </section>
  {% endif %}

    <!-- Main content -->
    <section class="content">

      <!-- Your Page Content Here -->
      {% block body %}{% endblock %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                  <span class="label label-danger pull-right">70%</span>
                </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- AdminLTE Option -->
<script>
    var AdminLTEOptions = {
        navbarMenuSlimscroll: true,
        navbarMenuSlimscrollWidth: "3px",
        navbarMenuHeight: "200px",
        directChat: {
            //Enable direct chat by default
            enable: true,
            //The button to open and close the chat contacts pane
            contactToggleSelector: '[data-widget="chat-pane-toggle"]'
        }
    };
</script>
<!-- AdminLTE App -->
<script src="{% static 'js/app.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

{% block footer %}{% endblock %}
</body>
</html>

templates/_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="retoohs, 科学上网, shadowsocks">
    <link rel="SHORTCUT ICON" href="{% static 'img/favicon.ico' %}" type="image/x-icon"/>
    <link rel="ICON" href="{% static 'img/favicon.ico' %}" type="image/ico"/>

    <title>Retoohs</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/flat-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jumbotron-narrow.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {#    <link href="asset/css/jumbotron-narrow.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'js/respond.min.js' %}"></script><![endif]-->
    {#    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>#}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.min.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?a1bff0c59495d14b9ab89245886a59b9";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>

</head>
<body>
<div class="container">
    <div class="header">
        <ul class="nav nav-pills pull-right" role="tablist">
{#            <li role="presentation"><a href="/">主页</a></li>#}
            {#        <li role="presentation"><a href="code.php">邀请码</a></li>#}
            <li role="presentation"><a href="{% url 'register' %}">注册</a></li>
            <li role="presentation"><a href="{% url 'login' %}">登录</a></li>
{#            <li role="presentation"><a href="about.php">关于</a></li>#}
        </ul>
        <h3 class="text-muted"><a href="/">retoohs</a></h3>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} text-center" role="alert"
                 style="padding: 5px; margin-bottom: 5px">{{ message |safe }}</div>
        {% endfor %}
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/base.html
{% load staticfiles %}
{% load avatar_tags %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Retoohs</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins -->
  <link rel="stylesheet" href="{% static 'css/skins/skin-blue.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="{% static 'js/html5shiv.min.js' %}"></script>
  <script src="{% static 'js/respond.min.js' %}"></script>
  <![endif]-->
  {% block head %}{% endblock %}
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>R</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>retoohs</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="/" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              {% avatar request.user class="user-image" %}
{#              <img src="{% static 'img/gravatar.png' %}" class="user-image" alt="User Image">#}
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'img/gravatar.png' %}" class="img-circle" alt="User Image">

                <p>
                  {{ request.user.username }}
                  <small>加入时间：{{ request.user.date_joined }}</small>
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{% url 'my' %}" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'logout' %}" class="btn btn-default btn-flat">登出</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          {% avatar request.user class="user-circle" %}
        </div>
        <div class="pull-left info">
          <p>{{ request.user.username }}</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header"></li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{% url 'lbforum_index' %}"><i class="fa fa-comment"></i> <span>论坛</span></a></li>
        <li><a href="{% url 'ss:index' %}"><i class="fa fa-user"></i> <span>用户中心</span></a></li>
        <li><a href="{% url 'ss:node_list' %}"><i class="fa fa-link"></i> <span>节点列表</span></a></li>
{#        <li><a href="#"><i class="fa fa-circle-o"></i> <span>修改资料</span></a></li>#}
        <li><a href="{% url 'ss:invite_code_list' %}"><i class="fa fa-code-fork"></i> <span>邀请码</span></a></li>
        <li><a href="{% url 'my' %}"><i class="fa fa-user-md"></i> <span>我的信息</span></a></li>
        <li><a href="{% url 'donate' %}"><i class="fa fa-credit-card"></i> <span>捐赠</span></a></li>
          {% if request.user.is_staff %}
        <li><a href="{% url 'ss:node_create' %}"><i class="fa fa-link"></i> <span>节点编辑</span></a></li>
        <li><a href="{% url 'ss:create_invite_code' %}"><i class="fa fa-link"></i> <span>邀请管理</span></a></li>
{#        <li><a href="#"><i class="fa fa-gears"></i> <span>系统信息</span></a></li>#}
          {% endif %}

      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <div class="content-wrapper">
  {% if page_header or page_msg %}
    <section class="content-header">
      <h1>
        {{ page_header }}
        <small>{{ page_msg }}</small>
      </h1>
    </section>
  {% endif %}

    <!-- Main content -->
    <section class="content">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert" style="padding: 5px; margin-bottom: 5px">{{ message |safe}}</div>
            {% endfor %}
        {% endif %}

      <!-- Your Page Content Here -->
      {% block body %}{% endblock %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
      <strong>Powered by <a href="https://github.com/youyaochi/retoohs">retoohs</a>.</strong>
  </footer>

  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- AdminLTE Option -->
<script>
    var AdminLTEOptions = {
        navbarMenuSlimscroll: true,
        navbarMenuSlimscrollWidth: "3px",
        navbarMenuHeight: "200px",
        directChat: {
            //Enable direct chat by default
            enable: true,
            //The button to open and close the chat contacts pane
            contactToggleSelector: '[data-widget="chat-pane-toggle"]'
        }
    };
</script>
<!-- AdminLTE App -->
<script src="{% static 'js/app.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

{% block footer %}{% endblock %}
</body>
</html>

templates/index.html
{% extends '_base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="jumbotron">
        <h2>retoohs</h2>
        <p class="lead">一颗赛艇</p>
        <p><a class="btn btn-lg btn-success" href="{% url 'ss:index' %}" role="button">立即注册</a></p>
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Android</h4>
            <p><a href="{% static 'clients/shadowsocks.apk' %}">影梭</a></p>
            <h4>Windows</h4>
            <p><a href="{% static 'clients/shadowsocks.zip' %}">Shadowsocks-windows</a></p>
        </div>

        <div class="col-lg-6">
            <h4>iOS</h4>
            <p><a href="https://itunes.apple.com/cn/app/id1148026741">Wingy</a></p>

            <h4>Mac OS</h4>
            <p><a href="{% static 'clients/shadowsocks.dmg' %}">ShadowsocksX-NG</a></p>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    {% crispy form %}
{% endblock %}

templates/logout.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <p class="text-center tile-title">已登出</p>
{#    <a href="{% url 'login' %}">login</a>#}
{% endblock %}

templates/register.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="col-md-6 col-md-offset-3">
    {% crispy form %}
    </div>
{% endblock %}

templates/stylesheet.html
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins -->
<link rel="stylesheet" href="{% static 'css/skins/skin-blue.min.css' %}">